apiVersion: v1
kind: Service
metadata:
  name: cluster-svc
  namespace: default  
  labels:
    env: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodeport: 30001
  selector:
      env: demo