apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: default  
  labels:
    env: demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
      env: demo